name = "rusmorph-download"
main = "src/index.ts"
compatibility_date = "2026-08-08"

[[r2_buckets]]
binding = "DOWNLOADS"
bucket_name = "namchieh-downloads"

[[routes]]
pattern = "namchieh.org/werus*"
zone_name = "namchieh.org"

[[routes]]
pattern = "namchieh.org/rusmorph*"
zone_name = "namchieh.org"

[[routes]]
pattern = "namchieh.org/update*"
zone_name = "namchieh.org"
